[workspace]
members = [
    "wasi-demo",
    "hello-world",
    "gcd",
    "memory",
    "answer",
    "log",
    "wasm-types",
    "trap",
    "cdylib",
    "cdylib-bindgen",
    "host-function",
    "fuel",
    "threads",
    "linking",
    "serialize",
]

