[package]
name = "host-function"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ['cdylib']

[dependencies]
## anyhow = "1.0.19"
## wasmtime = "0.27.0"
